// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Users$ReactTemplate = require("./Users.bs.js");
var Header$ReactTemplate = require("./Header.bs.js");
var Sidebar$ReactTemplate = require("./Sidebar.bs.js");

function str(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("App");

var displayFlex = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.flexWrap(Css.nowrap),
        /* :: */[
          Css.justifyContent(Css.spaceBetween),
          /* :: */[
            Css.alignItems(Css.stretch),
            /* [] */0
          ]
        ]
      ]
    ]);

var flexCol = Css.merge(/* :: */[
      displayFlex,
      /* :: */[
        Css.style(/* :: */[
              Css.flexDirection(Css.column),
              /* [] */0
            ]),
        /* [] */0
      ]
    ]);

var flexRow = Css.merge(/* :: */[
      displayFlex,
      /* :: */[
        Css.style(/* :: */[
              Css.flexDirection(Css.row),
              /* [] */0
            ]),
        /* [] */0
      ]
    ]);

var flexOne = Css.style(/* :: */[
      Css.flex(/* `num */[
            5496390,
            1.0
          ]),
      /* [] */0
    ]);

var Styles = /* module */[
  /* displayFlex */displayFlex,
  /* flexCol */flexCol,
  /* flexRow */flexRow,
  /* flexOne */flexOne
];

var appOptions = /* array */[
  "Users",
  "Roles",
  "Permissions"
];

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: flexCol
                        }, ReasonReact.element(undefined, undefined, Header$ReactTemplate.make(/* array */[])), React.createElement("div", {
                              className: flexRow
                            }, ReasonReact.element(undefined, undefined, Sidebar$ReactTemplate.make(appOptions, /* array */[])), ReasonReact.element(undefined, undefined, Users$ReactTemplate.make(flexOne, /* array */[]))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.str = str;
exports.component = component;
exports.Styles = Styles;
exports.appOptions = appOptions;
exports.make = make;
/* component Not a pure module */
