// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Axios = require("axios");
var ApolloLinks = require("reason-apollo/src/ApolloLinks.bs.js");
var ApolloLink = require("apollo-link");
var ReasonApollo = require("reason-apollo/src/ReasonApollo.bs.js");
var ApolloInMemoryCache = require("reason-apollo/src/ApolloInMemoryCache.bs.js");

var inMemoryCache = ApolloInMemoryCache.createInMemoryCache(undefined, undefined, /* () */0);

var httpLink = ApolloLinks.createHttpLink("http://localhost:8080/graphql", undefined, undefined, undefined, undefined, undefined, /* () */0);

var headerContextLink = ApolloLinks.createContextLink((function (param) {
        return {
                headers: {
                  "x-admin-token": "secret"
                }
              };
      }));

var instance = ReasonApollo.createApolloClient(ApolloLink.from(/* array */[
          headerContextLink,
          httpLink
        ]), inMemoryCache, undefined, undefined, undefined, undefined, /* () */0);

function login(param) {
  return Axios.post("http://localhost:8080/login", {
                  "x-admin-token": "secret"
                }).then((function (response) {
                  return Promise.resolve((console.log(response.data), /* () */0));
                })).catch((function (error) {
                return Promise.resolve((console.log(error), /* () */0));
              }));
}

exports.inMemoryCache = inMemoryCache;
exports.httpLink = httpLink;
exports.headerContextLink = headerContextLink;
exports.instance = instance;
exports.login = login;
/* inMemoryCache Not a pure module */
