// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var ApolloLinks = require("reason-apollo/src/ApolloLinks.bs.js");
var ApolloLink = require("apollo-link");
var ReasonApollo = require("reason-apollo/src/ReasonApollo.bs.js");
var ApolloInMemoryCache = require("reason-apollo/src/ApolloInMemoryCache.bs.js");

var inMemoryCache = ApolloInMemoryCache.createInMemoryCache(undefined, undefined, /* () */0);

var httpLink = ApolloLinks.createHttpLink("http://localhost:8080/graphql", undefined, undefined, undefined, undefined, undefined, /* () */0);

var headerContextLink = ApolloLinks.createContextLink((function (param) {
        return {
                headers: {
                  "X-Auth-Admin-Secret": "secret"
                }
              };
      }));

var instance = ReasonApollo.createApolloClient(ApolloLink.from(/* array */[
          headerContextLink,
          httpLink
        ]), inMemoryCache, undefined, undefined, undefined, undefined, /* () */0);

exports.inMemoryCache = inMemoryCache;
exports.httpLink = httpLink;
exports.headerContextLink = headerContextLink;
exports.instance = instance;
/* inMemoryCache Not a pure module */
